# Generated by Django 5.2.2 on 2026-05-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='enrichment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='enrichment_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='enrichment_status',
            field=models.CharField(choices=[('raw', 'Raw'), ('pending_enrichment', 'Pending Enrichment'), ('enriching', 'Enriching'), ('enriched', 'Enriched'), ('failed', 'Failed')], default='raw', max_length=30),
        ),
    ]
