# Generated by Django 5.2.2 on 2026-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_question_provenance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='distractor_explanations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
