# Generated by Django 5.2.2 on 2026-05-25 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_question_distractor_explanations'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='snippet_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='snippet_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='snippet_line_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=2),
        ),
    ]
