# Generated by Django 5.2.2 on 2026-05-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_questionattachment'),
        ('question', '0011_question_snippet_fields'),
    ]

    operations = [
    ]
