# Generated by Django 5.2.2 on 2026-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_merge_20260529_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='snippet_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
