# Generated by Django 5.2.2 on 2026-08-12 18:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_question_snippet_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('numerical', 'Numerical')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='tolerance',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correct_index__isnull', False), ('correct_value__isnull', True), ('options__isnull', False), ('response_type', 'mcq')), models.Q(('correct_index__isnull', True), ('correct_value__isnull', False), ('options__isnull', True), ('response_type', 'numerical')), _connector='OR'), name='question_type_field_consistency'),
        ),
    ]
