# Generated by Django 5.2.2 on 2026-08-24 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_rename_code_snippet_to_snippet_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=20)),
                ('directions_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
                'db_table': 'question_sets',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='position_in_set',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.questionset'),
        ),
    ]
