# Generated by Django 5.2.2 on 2026-08-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_questionset_question_position_in_set_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
