# Generated by Django 5.2.2 on 2026-08-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_question_image_url_questionset_image_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='question_type_field_consistency',
        ),
        migrations.AddField(
            model_name='question',
            name='common_trap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='shortcut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_ref',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_topic',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='technique_tag',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('numerical', 'Numerical'), ('short_answer', 'Short Answer')], default='mcq', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correct_answer_text__isnull', True), ('correct_index__isnull', False), ('correct_value__isnull', True), ('options__isnull', False), ('response_type', 'mcq')), models.Q(('correct_answer_text__isnull', True), ('correct_index__isnull', True), ('correct_value__isnull', False), ('options__isnull', True), ('response_type', 'numerical')), models.Q(('correct_answer_text__isnull', False), ('correct_index__isnull', True), ('correct_value__isnull', True), ('options__isnull', True), ('response_type', 'short_answer')), _connector='OR'), name='question_type_field_consistency'),
        ),
    ]
