# Generated by Django 5.2.2 on 2026-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_remove_question_question_type_field_consistency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='question_type_field_consistency',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer_text',
        ),
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('numerical', 'Numerical')], default='mcq', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correct_index__isnull', False), ('correct_value__isnull', True), ('options__isnull', False), ('response_type', 'mcq')), models.Q(('correct_index__isnull', True), ('correct_value__isnull', False), ('options__isnull', True), ('response_type', 'numerical')), _connector='OR'), name='question_type_field_consistency'),
        ),
    ]
