# Generated by Django 5.2.2 on 2026-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_remove_question_question_type_field_consistency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='table_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='table_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_url__isnull', True), ('table_data__isnull', False)), models.Q(('image_url__isnull', False), ('table_data__isnull', True)), models.Q(('image_url__isnull', True), ('table_data__isnull', True)), _connector='OR'), name='questionset_stimulus_exclusivity'),
        ),
    ]
