# Generated by Django 5.2.2 on 2026-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_questionset_table_data_questionset_table_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionset',
            name='questionset_stimulus_exclusivity',
        ),
        migrations.AddField(
            model_name='questionset',
            name='stimulus_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_url__isnull', True), ('stimulus_text__isnull', True), ('table_data__isnull', True)), models.Q(('image_url__isnull', True), ('stimulus_text__isnull', True), ('table_data__isnull', False)), models.Q(('image_url__isnull', False), ('stimulus_text__isnull', True), ('table_data__isnull', True)), models.Q(('image_url__isnull', True), ('stimulus_text__isnull', False), ('table_data__isnull', True)), _connector='OR'), name='questionset_stimulus_exclusivity'),
        ),
    ]
