# Generated by Django 5.2.2 on 2026-10-01 22:59

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('question_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('want_more_practice', 'Want more practice like this'), ('new_concept', 'New concept, want to revisit'), ('good_example', 'Good example to reference later'), ('curious', 'Just curious / interesting problem')], max_length=30)),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='bookmarks_b_user_id_f7315e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlagSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('question_id', models.UUIDField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('answer_or_explanation_wrong', 'Answer or explanation seems wrong'), ('options_unclear_or_not_distinct', "Options don't make sense / aren't distinct"), ('missing_table_image_or_related_question', 'Missing table, image, or related question'), ('confusing_wording', 'Confusing or unclear wording'), ('something_else', 'Something else')], max_length=50), default=list, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['question_id', 'status'], name='bookmarks_f_questio_2a63c0_idx')],
            },
        ),
    ]
