# Generated by Django 5.2.2 on 2026-01-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
    ]
