# Generated by Django 5.2.2 on 2026-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_answer_unique_together_delete_questionattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
