# Generated by Django 5.2.2 on 2026-05-29 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_answer_daily_session'),
        ('question', '0003_questionattachment'),
        ('roadmap', '0021_session_attempt_and_session_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('topic_type', models.CharField(choices=[('weakness', 'Weakness'), ('new', 'New'), ('review', 'Review')], max_length=20)),
                ('selected_index', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('time_to_first_tap_ms', models.IntegerField(blank=True, null=True)),
                ('answer_changed', models.BooleanField(default=False)),
                ('bloom_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('sequence_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attempts', to='roadmap.dailysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Attempt',
                'verbose_name_plural': 'Session Attempts',
                'db_table': 'session_attempts',
            },
        ),
    ]
