# Generated by Django 5.2.2 on 2026-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_session_attempt_and_session_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattempt',
            name='submitted_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
