# Generated by Django 5.2.2 on 2026-01-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_alter_roadmap_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roadmap',
            unique_together=set(),
        ),
    ]
