# Generated by Django 5.2.2 on 2026-01-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_alter_roadmap_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapquestion',
            name='status',
            field=models.CharField(choices=[('answered', 'Answered'), ('unanswered', 'Unanswered')], default='unanswered', max_length=50),
        ),
    ]
