# Generated by Django 5.2.2 on 2026-01-30 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_roadmapquestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
