# Generated by Django 5.2.2 on 2026-02-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_roadmap_subject_roadmap_topics_alter_roadmap_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='avg_difficulty',
            field=models.CharField(choices=[('medium', 'Medium'), ('easy', 'Easy'), ('hard', 'Hard')], default='Medium', max_length=20),
        ),
    ]
