# Generated by Django 5.2.2 on 2026-02-06 03:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_roadmap_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='search_vector_smpl',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_en'], name='roadmaps_search__7c3501_gin'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_smpl'], name='roadmaps_search__a0b435_gin'),
        ),
    ]
