# Generated by Django 5.2.2 on 2026-02-06 13:28

from django.db import migrations, models

def backfill_search_vector(apps,schema_editor):
    Roadmap = apps.get_model("roadmap","Roadmap")
    Roadmap.objects.all().update(title = models.F("title"))
    

class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0013_update_search_trigger'),
    ]

    operations = [
        migrations.RunPython(backfill_search_vector),
    ]
