# Generated by Django 5.2.2 on 2026-02-09 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0014_roadmap_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='progress_percntg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
