# Generated by Django 5.2.2 on 2026-03-06 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0017_remove_roadmapjob_result_roadmapjob_roadmap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roadmapjob',
            name='roadmap_roa_user_id_2828f8_idx',
        ),
        migrations.AddIndex(
            model_name='roadmapjob',
            index=models.Index(fields=['user', 'status', 'created_at'], name='roadmap_roa_user_id_b3b250_idx'),
        ),
    ]
