# Generated by Django 5.2.2 on 2026-05-18 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0018_remove_roadmapjob_roadmap_roa_user_id_2828f8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('payload_json', models.JSONField()),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_sessions',
                'indexes': [models.Index(fields=['user', 'date'], name='daily_sessi_user_id_f86b04_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'roadmap', 'date'), name='unique_daily_session_per_roadmap')],
            },
        ),
    ]
