# Generated by Django 5.2.2 on 2026-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0020_dailysession_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
