# Generated by Django 5.2.2 on 2026-07-03 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('roadmap', '0021_session_attempt_and_session_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sessions', to='enrollments.courseenrollment'),
        ),
    ]
