# Generated by Django 5.2.2 on 2026-07-05 13:41

from django.db import migrations, models


def backfill_completed_status(apps, schema_editor):
    DailySession = apps.get_model('roadmap', 'DailySession')
    DailySession.objects.filter(is_completed=True).update(status='COMPLETED')


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0022_dailysession_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded')], default='READY', max_length=20),
        ),
        migrations.RunPython(backfill_completed_status, migrations.RunPython.noop),
    ]
