# Generated by Django 5.2.2 on 2026-08-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0023_dailysession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
