steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'servers/catalyst/Dockerfile'
      - '-t'
      - 'asia-south2-docker.pkg.dev/catalyst-be/catalyst-main/catalyst-main:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south2-docker.pkg.dev/catalyst-be/catalyst-main/catalyst-main:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - catalyst-main
      - --image=asia-south2-docker.pkg.dev/catalyst-be/catalyst-main/catalyst-main:$COMMIT_SHA
      - --region=asia-south2
      - --platform=managed
      - --memory=2Gi
      - --cpu=2
      - --timeout=600
      - --max-instances=5
      - --allow-unauthenticated
      - --set-secrets=HF_TOKEN=HF_TOKEN:latest
      - --set-secrets=VECTOR_DB_URL=VECTOR_DB_URL:latest
      - --set-secrets=VECTOR_DB_KEY=VECTOR_DB_KEY:latest
      - --set-secrets=QLOO_API_KEY=QLOO_API_KEY:latest
      - --set-secrets=QLOO_BASE_URL=QLOO_BASE_URL:latest
      - --set-secrets=VAPID_PUBLIC_KEY=VAPID_PUBLIC_KEY:latest
      - --set-secrets=VAPID_PRIVATE_KEY=VAPID_PRIVATE_KEY:latest
      - --set-secrets=CEREBRAS_API_KEY=CEREBRAS_API_KEY:latest

images:
  - 'asia-south2-docker.pkg.dev/catalyst-be/catalyst-main/catalyst-main:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
