# Generated by Django 5.2.2 on 2026-01-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_target_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_goal_onboarding',
            field=models.CharField(choices=[('school exams', 'School Exams'), ('competitive exams', 'Competitive Exams'), ('university semester exams', 'University Semester Exams'), ('professional certification', 'Professional Certification'), ('general knowledge', 'General Knowledge')], default='other', max_length=26),
        ),
    ]
