# Generated by Django 5.2.2 on 2026-03-06 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_daily_target_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_attempted', models.IntegerField(default=0)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('easy_correct', models.IntegerField(default=0)),
                ('medium_correct', models.IntegerField(default=0)),
                ('hard_correct', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_attempted', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='users_userd_user_id_87d6ad_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
