# Generated by Django 5.2.2 on 2026-03-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userstats_userdailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='PLATFORM', max_length=255),
        ),
    ]
