# Generated by Django 5.2.2 on 2026-01-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.TextField(unique=True),
        ),
    ]
