# Generated by Django 5.2.2 on 2026-07-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_accuracy', models.JSONField(default=dict)),
                ('weekly_sessions_completed', models.IntegerField(default=0)),
                ('weekly_accuracy', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='enrollments.courseenrollment')),
            ],
            options={
                'db_table': 'user_course_profiles',
            },
        ),
    ]
