# Generated by Django 5.2.2 on 2026-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_usercourseprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprofile',
            name='previous_week_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
